In [47]:

import pandas as pd

from sklearn import metrics


inputfile = '../../test/data/test4.csv'
outputfile1 = '../tmp/cm_train1.xls' 
outputfile2 = '../tmp/cm_test1.xls' 
data = pd.read_csv(inputfile, encoding = 'utf8') 
data = data.as_matrix()

In [48]:
import numpy as np


In [49]:
from numpy.random import shuffle 
shuffle(data) 
data_train = data[:int(0.8*len(data)), :] 
data_test = data[int(0.8*len(data)):, :] 

In [50]:
x_train = data_train[:, 2:]*30
y_train = data_train[:, 0].astype(int)
x_test = data_test[:, 2:]*30
y_test = data_test[:, 0].astype(int)

In [51]:
y_train,y_test

(array([5, 3, 3, 3, 3, 3, 3, 2, 4, 2, 3, 4, 1, 3, 3, 1, 3, 1, 2, 2, 2, 4, 3,
        3, 3, 1, 3, 4, 2, 2, 3, 4, 3, 1, 2, 2, 3, 3, 5, 1, 2, 2, 2, 1, 3, 2,
        3, 1, 3, 3, 2, 1, 1, 3, 3, 1, 2, 5, 5, 1, 3, 3, 3, 2, 3, 3, 1, 1, 4,
        3, 3, 2, 3, 1, 3, 4, 3, 3, 1, 3, 2, 1, 3, 3, 3, 3, 5, 2, 3, 4, 1, 4,
        3, 1, 3, 1, 1, 1, 3, 3, 1, 4, 2, 2, 1, 3, 1, 3, 3, 4, 1, 4, 3, 1, 3,
        2, 3, 2, 1, 3, 2, 3, 2, 3, 3, 1, 1, 1, 3, 4, 2, 1, 4, 1, 2, 4, 1, 1,
        3, 2, 4, 2, 3, 3, 3, 2, 2, 3, 4, 2, 2, 3, 1, 1, 3, 3, 2, 1, 4, 2, 5,
        3]),
 array([2, 1, 2, 3, 3, 3, 1, 1, 4, 3, 1, 2, 3, 2, 3, 1, 1, 4, 3, 3, 3, 2, 2,
        1, 3, 1, 2, 4, 2, 3, 4, 2, 3, 1, 3, 1, 4, 1, 4, 1, 1]))

In [52]:
from sklearn import svm
model = svm.SVC()
model.fit(x_train, y_train)
import pickle
pickle.dump(model, open('../tmp/svm4.model', 'wb'))



In [53]:
y_test,model.predict(x_test)

(array([2, 1, 2, 3, 3, 3, 1, 1, 4, 3, 1, 2, 3, 2, 3, 1, 1, 4, 3, 3, 3, 2, 2,
        1, 3, 1, 2, 4, 2, 3, 4, 2, 3, 1, 3, 1, 4, 1, 4, 1, 1]),
 array([2, 1, 2, 3, 3, 3, 1, 1, 4, 3, 1, 2, 3, 2, 3, 1, 1, 4, 3, 3, 3, 2, 2,
        1, 3, 1, 2, 4, 2, 3, 4, 2, 3, 1, 3, 3, 4, 1, 4, 1, 1]))

In [20]:
outputfile1 = '../tmp/cm_train2.xls' 
outputfile2 = '../tmp/cm_test2.xls' 

cm_train = metrics.confusion_matrix(y_train, model.predict(x_train)) 
cm_test = metrics.confusion_matrix(y_test, model.predict(x_test)) 

pd.DataFrame(cm_train, index = range(1, 6), columns = range(1, 6)).to_excel(outputfile1)
pd.DataFrame(cm_test, index = range(1, 6), columns = range(1, 6)).to_excel(outputfile2)

In [54]:
metrics.confusion_matrix(y_train, model.predict(x_train))

array([[35,  1,  2,  0,  0],
       [ 0, 34,  1,  0,  0],
       [ 0,  0, 65,  0,  0],
       [ 0,  0,  3, 15,  0],
       [ 0,  1,  0,  3,  2]])

In [55]:
metrics.confusion_matrix(y_test, model.predict(x_test))

array([[12,  0,  1,  0],
       [ 0,  9,  0,  0],
       [ 0,  0, 13,  0],
       [ 0,  0,  0,  6]])

In [56]:
model.score(x_test, y_test)

0.97560975609756095

In [30]:
cm_train

array([[36,  1,  3,  0,  0],
       [ 0, 36,  0,  0,  0],
       [ 0,  0, 61,  0,  0],
       [ 0,  0,  2, 18,  0],
       [ 0,  1,  1,  1,  2]])

In [57]:
def ordinalData(tabledata, category=['C1','C2','C3','C4','C5']):
    n=len(tabledata)
    Span_data=np.array([])
    for k in range(n+1):
      if k==0:
         column_ex= np.append(np.array(['Real\Pred']),category)
         column_ex= np.append(column_ex,'Total')   
         #column_ex= np.append(np.array([' \ ']),category)   
         Span_data=np.append(Span_data,column_ex)
      else:
         Sdata=np.array([category[-k]])
         total=  np.sum(tabledata[-k]) 
         Sdata=np.append(Sdata,tabledata[-k])
         Sdata=np.append(Sdata,total)   
         Span_data=np.append(Span_data,Sdata)
    # sum for each pre-Category data        
    Span_data= np.append(Span_data,'Total')        
    Span_data= np.append(Span_data,np.sum(tabledata,axis=0))
    Span_data= np.append(Span_data,np.sum(tabledata))        
    Span_data=Span_data.reshape([n+2,n+2])
    
    return Span_data

In [58]:
def SvenssonTable(tabledata):
    Sdata=ordinalData(tabledata)
    n=len(tabledata)
    make_table(Sdata)

    apply_theme('basic_both')
    set_cell_style(0,0, thick_border='left,top')
    #set_cell_style(0, 0, color='lightblack')
    set_column_style(0, color='lightgray')
    for i in range(1,n+1):
        set_cell_style(i,n+1-i, thick_border='all',color="lightbrown")

    return set_cell_style(0, 0, color='orange')

In [59]:
from ipy_table import make_table,apply_theme,set_cell_style,set_column_style,set_row_style
from IPython.display import clear_output, display

In [60]:
p=SvenssonTable(cm_train)


In [61]:
display(p)